### ISSUE TITLE
Spacing in Abstract page

### ISSUE THREAD

**Issue by clukewatson** [amunn/msu-thesis#9] opened 2021-05-15 21:00 UTC
Howdy,

The spacing between the word "Abstract" and the title of the thesis needs to be doublespaced but it is currently slightly greater. [See the example page](https://grad.msu.edu/sites/default/files/content/etd/Sample%20Abstract%20Page.pdf).

They don't seem to catch this one frequently but it is the rule.

**Comment by amunn** [comment] 2021-05-16 13:00
Hi thanks for the report. Were you using v2.8? If so I think this is fixed with the latest version. If you have a current TeX Live or MikTeX you should just be able to update. If you're using Overleaf, you can download from here. The problem is that "double spaced" is ill-defined, and the thesis office measures inconsistently.   If they still complain, use `\setlength{\onelineskip}{12pt}` in your preamble.

**Comment by clukewatson** [comment] 2021-05-16 14:06
I don't know many technical details. I'm using a 2020 TeX Live via texmaker on my computer, but my Overleaf version has the same issue. In the Overleaf, `\setlength{\onelineskip}{12pt}` did not change anything. I can share my Overleaf file if you want. 

I ended up just manually creating the page so no rush on my end.

**Comment by amunn** [comment] 2021-05-16 14:09
If you're using a 2020 version then you're using v 2.8; Try it with the newest version here (then the `\setlength` command will also have an effect.)

**Closed as completed** 2021-07-01 22:03 UTC
